//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public string imdbID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Synopsis { get; set; }
        public string Cast { get; set; }
    }
}
